//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSImageView, NSString, NSTextField;

@interface DialogController : NSWindowController
{
    NSString *_helpAnchor;
    NSString *_actionID;
    NSButton *_okButton;
    NSButton *_helpButton;
    NSTextField *_titleText;
    NSTextField *_messageText;
    NSImageView *_iconImageView;
}

@property(retain, nonatomic) NSString *actionID; // @synthesize actionID=_actionID;
@property(retain, nonatomic) NSString *helpAnchor; // @synthesize helpAnchor=_helpAnchor;
@property(readonly, nonatomic) NSString *dialogTitle;
@property(readonly, nonatomic) NSString *dialogMessage;
- (void)setOkButton:(id)arg1;
- (void)setHelpButton:(id)arg1;
- (void)setIconImage:(id)arg1;
- (void)setTitleText:(id)arg1;
- (void)setMessageText:(id)arg1;
- (void)buttonPressed:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)dealloc;
- (id)initWithWindowNibPath:(id)arg1 withID:(id)arg2;

@end

