//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DisplayState, NSTimer;

@interface DisplayStateMachine : NSObject
{
    BOOL _brightIncKeyDown;
    BOOL _brightDecKeyDown;
    BOOL _mirrorKeyDown;
    BOOL _hasBuiltinKeyboard;
    DisplayState *_currentState;
    long long _graphicType;
    int _eventType;
    int _displayID;
    float _brightness;
    NSTimer *_repeatKeyTimer;
    int _repeatKeyEvent;
}

+ (id)alloc;
+ (void)stopSingleton;
+ (void)releaseSingleton;
+ (id)getSingleton;
@property int _eventType; // @synthesize _eventType;
@property(retain) DisplayState *_currentState; // @synthesize _currentState;
@property BOOL _hasBuiltinKeyboard; // @synthesize _hasBuiltinKeyboard;
@property BOOL _mirrorKeyDown; // @synthesize _mirrorKeyDown;
@property BOOL _brightIncKeyDown; // @synthesize _brightIncKeyDown;
@property BOOL _brightDecKeyDown; // @synthesize _brightDecKeyDown;
- (void)powerChanged:(id)arg1;
- (void)handleSleepEvent:(BOOL)arg1;
- (void)handleKeyEvent:(int)arg1 shift:(BOOL)arg2 control:(BOOL)arg3 option:(BOOL)arg4 command:(BOOL)arg5 pressed:(BOOL)arg6;
- (void)generateRepeatKeyEvent:(id)arg1;
- (void)createRepeatKeyTimer:(int)arg1;
- (void)clearRepeatKeyTimer;
- (void)convertExternalKeyboardEvents:(int *)arg1 shift:(char *)arg2 control:(char *)arg3 option:(char *)arg4 command:(char *)arg5 pressed:(BOOL)arg6;
- (void)getEmbeddedKeyboardDisplayID:(BOOL)arg1;
- (void)getDisplayID:(int)arg1 alternateDisplay:(BOOL)arg2;
- (void)getExternalKeyboardDisplayID:(BOOL)arg1;
- (BOOL)hasBuiltInKeyboard;
- (void)displayOSD;
- (void)changeBrightnessBy:(int)arg1 type:(int)arg2;
- (void)logExternalDisplayMode:(int)arg1;
- (void)switchExternalDisplayMode;
- (void)detectDisplaysOnThread:(id)arg1;
- (void)detectDisplays;
- (void)mirrorDisplays;
- (void)displayPrefs;
- (void)stop;
- (void)dealloc;
- (id)init;

@end

