//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "KeyboardALSAlgorithm.h"

@interface KeyboardALSAlgorithmHID : KeyboardALSAlgorithm
{
    int _deviceProductID;
    unsigned int _driver;
    struct IONotificationPort *_notificationPort;
    struct __CFRunLoop *_runLoop;
    unsigned int _connectIterator;
    unsigned int _disconnectIterator;
    float _lastValueSet;
    int _lastFadeSpeed;
}

- (void)setHardwareBrightness:(float)arg1 UsingFadeSpeed:(int)arg2;
- (void)setDriverSuppressed;
- (void)sendDriverValue:(float)arg1 UsingFadeSpeed:(int)arg2;
- (void)dealloc;
- (BOOL)setupDriver;
- (void)deviceTerminatedHandler:(unsigned int)arg1;
- (_Bool)shouldUseAdjustedBrightnessCurve;
- (void)deviceArrivalHandler:(unsigned int)arg1;
- (id)init;

@end

