//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "KeyboardALSAlgorithm.h"

@interface KeyboardALSAlgorithmLegacy : KeyboardALSAlgorithm
{
    unsigned int _legacyDriver;
}

- (void)setHardwareBrightness:(float)arg1 UsingFadeSpeed:(int)arg2;
- (void)setDriverSuppressed;
- (void)dealloc;
- (BOOL)setupDriver;
- (id)init;

@end

