//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SystemListener : NSObject
{
    BOOL _onConsole;
    int _currentReducedBrightnessSetting;
    struct __CFString *_IOPMDynamicStoreSettingsKey;
    struct __SCDynamicStore *_SCDynamicStore;
    struct __CFRunLoopSource *_powerMonitoringRunLoopSourceRef;
    unsigned int _displayNotification;
    struct IONotificationPort *_displayNotifyPort;
    unsigned int _pmRootNotification;
    struct IONotificationPort *_pmRootNotificationPort;
    unsigned int _systemPowerRootPort;
    unsigned int _systemPowerNotifier;
    struct IONotificationPort *_powerNotifyPort;
}

+ (id)alloc;
+ (void)stopSingleton;
+ (void)releaseSingleton;
+ (id)getSingleton;
- (void)handlePMRootChange:(unsigned int)arg1 msgArg:(void *)arg2 service:(unsigned int)arg3;
- (void)handleSystemPowerChange:(unsigned int)arg1 msgArg:(void *)arg2;
- (void)setDisplayDimState:(_Bool)arg1;
- (void)bumpBrightnessDown;
- (void)bumpBrightnessUp;
- (float)getBrightnessBumpFloor;
- (void)setBrightnessLevel:(int)arg1;
- (int)brightnessLevel;
- (void)powerConfigurationChanged;
- (void)stopMagsafePowerMonitoring;
- (void)startMagsafePowerMonitoring;
- (void)stopPMRootMonitoring;
- (void)startPMRootMonitoring;
- (void)stopDisplayPowerMonitoring;
- (void)startDisplayPowerMonitoring;
- (void)screenIsUnlocked:(id)arg1;
- (void)screenIsLocked:(id)arg1;
- (BOOL)isOnConsole;
- (void)movedOffConsole:(id)arg1;
- (void)movedOnConsole:(id)arg1;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)init;

@end

