//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSUserNotificationCenterDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSTimer;
@protocol OS_dispatch_queue;

@interface DriverServices : NSObject <NSUserNotificationCenterDelegate>
{
    unsigned int _masterPort;
    struct IONotificationPort *_notificationPort;
    NSMutableDictionary *_messageDict;
    NSMutableDictionary *_actionDict;
    NSMutableDictionary *_serviceDict;
    NSMutableDictionary *_pendingActions;
    NSMutableDictionary *_preferencesV2;
    NSMutableDictionary *_preferencesV3;
    NSMutableDictionary *_helpAnchorForNotification;
    NSMutableDictionary *_deviceTypeForNotification;
    NSMutableDictionary *_deviceEraForNotifciation;
    NSMutableSet *_listenedClasses;
    NSMutableArray *_dialogs;
    NSMutableArray *_notifications;
    NSTimer *_generateBatteryAlertsTimer;
    NSTimer *_enableConnectionActionsTimer;
    BOOL _enableConnectionActions;
    BOOL _enableNotificationCenterActions;
    NSObject<OS_dispatch_queue> *_pref_queue;
    NSMutableDictionary *_reportsBatteryPercent;
}

+ (id)alloc;
+ (void)stopSingleton;
+ (void)releaseSingleton;
+ (id)getSingleton;
@property(readonly) NSMutableDictionary *reportsBatteryPercent; // @synthesize reportsBatteryPercent=_reportsBatteryPercent;
@property BOOL enableNotificationCenterActions; // @synthesize enableNotificationCenterActions=_enableNotificationCenterActions;
- (BOOL)serviceReportsBatteryPercentage:(unsigned int)arg1;
- (int)getBatteryStatusFlags:(unsigned int)arg1;
- (int)getBatteryPercent:(unsigned int)arg1;
- (struct __CFString *)getPrefHostName;
- (struct __CFString *)getPrefUserName;
- (id)getLocalizedString:(id)arg1 withBundle:(id)arg2;
- (id)getDialogWindowNibPath;
- (id)getLocalizedNibPath;
- (BOOL)isKeyboardActive;
- (BOOL)isMouseActive;
- (id)createPrefixIDFromBundleID:(id)arg1 andClass:(id)arg2;
- (void)expandPathForKey:(id)arg1 inDictionary:(id)arg2 withPrefix:(id)arg3;
- (id)getDeviceAddress:(unsigned int)arg1;
- (id)getKeyForServiceDictionary:(unsigned int)arg1;
- (void)batteryTimerFired:(id)arg1;
- (void)closeDialog:(id)arg1;
- (void)generateBatteryAlertsFired:(id)arg1;
- (void)generateBatteryAlerts;
- (id)getPrefixIDForService:(unsigned int)arg1;
- (void)launchHelpWindowForNotification:(id)arg1;
- (void)launchSystemPreferencesBatteryChangeHelpForNotification:(id)arg1;
- (void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2;
- (void)dismissLowBatteryNotificationForService:(unsigned int)arg1;
- (void)writeBatteryPercentToPrefsForService:(unsigned int)arg1;
- (void)dispatchDialogAction:(id)arg1;
- (void)dispatchOSDAction:(id)arg1;
- (void)dispatchNotificationCenterAction:(id)arg1 forDevice:(id)arg2;
- (void)dispatchPendingAction:(id)arg1;
- (void)dispatchAction:(id)arg1 forDevice:(id)arg2;
- (BOOL)cancelDisconnectForMessage:(id)arg1 forService:(unsigned int)arg2 andAction:(id)arg3;
- (BOOL)isActionCanceled:(id)arg1 forMessage:(id)arg2 withName:(id)arg3 andService:(unsigned int)arg4;
- (BOOL)isActionDelayed:(id)arg1 actionDictionary:(id)arg2 actionName:(id)arg3 service:(unsigned int)arg4;
- (void)respondToMessage:(id)arg1 forService:(unsigned int)arg2;
- (void)processMsgForService:(unsigned int)arg1 messageType:(unsigned int)arg2 messageArgument:(void *)arg3;
- (void)deviceArrived:(unsigned int)arg1;
- (void)setPreferences:(id)arg1 capabilityID:(unsigned int)arg2 withDictionary:(id)arg3;
- (id)getPreferences:(id)arg1 capabilityID:(unsigned int)arg2;
- (id)getPreference:(id)arg1 capabilityID:(unsigned int)arg2 forKey:(id)arg3;
- (void)powerChanged:(id)arg1;
- (void)preferencesChanged:(id)arg1;
- (void)cachePreferencesForDevice:(unsigned int)arg1 preferenceID:(id)arg2 capabilityID:(unsigned int)arg3 resetDefaults:(BOOL)arg4 resetCache:(BOOL)arg5;
- (id)generateCurrentPreferencesForPreferenceID:(id)arg1 capabilityID:(unsigned int)arg2;
- (id)generateCurrentPreferencesForDevice:(unsigned int)arg1 preferenceID:(id)arg2 capabilityID:(unsigned int)arg3 resetDefaults:(BOOL)arg4 resetCache:(BOOL)arg5;
- (void)setPrefs:(id)arg1 forDevice:(unsigned int)arg2;
- (void)sendPreferencesToDevice:(unsigned int)arg1 resetDefaults:(BOOL)arg2 resetCache:(BOOL)arg3;
- (void)sendPreferencesToAllV3DevicesWithPrefID:(id)arg1 resetDefaults:(BOOL)arg2 resetCache:(BOOL)arg3;
- (void)sendPreferencesToAllDevicesWithPrefId:(id)arg1 resetDefaults:(BOOL)arg2 resetCache:(BOOL)arg3;
- (void)createV2PreferencesForClass:(id)arg1 resetDefaults:(BOOL)arg2;
- (void)storeDefaultV2PrefsForClasses:(id)arg1 withBundleID:(id)arg2;
- (void)enableConnectionActionsTimerFired:(id)arg1;
- (void)releaseNotifications;
- (void)invalidateTimers;
- (int)createNotificationPort;
- (void)listenForClass:(id)arg1;
- (void)installListenersForClasses:(id)arg1 withBundleID:(id)arg2 withResourceBundle:(id)arg3;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

