//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;
@protocol OS_dispatch_source;

@interface KeyboardALSAlgorithm : NSObject
{
    struct __IOHIDEventSystemClient *_hidSystemRef;
    struct __IOHIDServiceClient *_alsController;
    int _lgpVersion;
    NSObject<OS_dispatch_source> *_forceUpdateTimer;
    float _currentLux;
    float _brightness;
    _Bool _saturated;
    _Bool _canAdjust;
    _Bool _keybdAlsEnabled;
    _Bool _suppressed;
    _Bool _dimmed;
    _Bool _displayDimmed;
    _Bool _userInactive;
    _Bool _muted;
    int _pwmMin;
    int _pwmMax;
    int _pwmOff;
    float _ambientOffset;
    float _ambientSlope;
    float _ambientLowThreshold;
    float _ambientHighThreshold;
    _Bool _suspendAls;
    _Bool _defaultOff;
    BOOL _ready;
    NSTimer *_keyDimTimer;
    int _keyDimTime;
    CDUnknownFunctionPointerType _eos_device_is_supported_ptr;
    void *_embedded_os_support_handler;
}

+ (id)alloc;
+ (void)stopSingleton;
+ (void)releaseSingleton;
+ (id)getSingleton;
@property void *embedded_os_support_handler; // @synthesize embedded_os_support_handler=_embedded_os_support_handler;
@property CDUnknownFunctionPointerType eos_device_is_supported_ptr; // @synthesize eos_device_is_supported_ptr=_eos_device_is_supported_ptr;
@property _Bool userInactive; // @synthesize userInactive=_userInactive;
@property _Bool suspendAls; // @synthesize suspendAls=_suspendAls;
- (void)forceUpdate:(unsigned int)arg1;
- (void)destroyALSController;
- (_Bool)createALSController;
- (void)endKeyDim;
- (void)keyDimTimer:(id)arg1;
- (void)listenToAllMouseKeyboardEvents:(BOOL)arg1;
- (void)resetKeyDimTimer;
@property _Bool dimmed;
- (void)setKeyboardOffsetToCurrentAmbient:(float)arg1;
- (_Bool)shouldUseAdjustedBrightnessCurve;
- (float)calculateKeyboardBrightnessAtAmbient:(float)arg1;
- (float)luxToAmbient:(float)arg1;
- (void)setHardwareBrightness:(float)arg1 UsingFadeSpeed:(int)arg2;
- (void)prefChanged:(id)arg1;
- (void)handleALSUpdate:(float)arg1;
- (float)alsLuxToNits:(float)arg1;
- (float)kbNitsToPWMPercentage:(float)arg1;
- (void)pmRootChanged:(id)arg1;
- (void)movedOnConsole:(id)arg1;
- (void)movedOffConsole:(id)arg1;
@property float brightness;
@property _Bool saturated;
@property _Bool canAdjust;
@property _Bool muted;
- (void)toggleMute;
- (void)setDriverSuppressed;
- (void)updateCurveForCurrentLux:(float)arg1 userSelectedBrightness:(float)arg2;
@property _Bool suppressed;
- (_Bool)checkKeyboardFeatureDisable;
- (id)description;
- (void)getALSPreferences;
- (struct __CFDictionary *)copyCurveDictionary;
- (void)updateCurveWithDictionary:(struct __CFDictionary *)arg1;
- (void)unregisterALSCallbacks;
- (_Bool)registerALSCallbacks;
- (void)stop;
- (void)dealloc;
- (void)setupDriverDone;
- (BOOL)setupDriver;
- (int)getLGPVersion;
- (id)init;
- (void)initEOS;
- (_Bool)eos_device_is_supported;

@end

