//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface MsgTracerLogger : NSObject
{
    NSTimer *_bezelKeyReportTimer;
    unsigned int _brightnessChangeCount;
    unsigned int _keyboardBrightnessChangeCount;
    unsigned int _volumeMuteCount;
    unsigned int _volumeChangeCount;
    unsigned int _mediaPlayPause;
    unsigned int _mediaChange;
    unsigned int _ejectCount;
}

+ (id)alloc;
+ (void)stopSingleton;
+ (void)releaseSingleton;
+ (id)getSingleton;
- (void)logEject;
- (void)logMediaPlayPause;
- (void)logMediaChange;
- (void)logVolumeMute;
- (void)logVolumeChange;
- (void)logKeyboardBrightnessChange;
- (void)logBrightnessChange;
- (void)resetBezelKeyStats;
- (void)logBezelKeyStats:(id)arg1;
- (void)logCGSEvent:(struct _CGSEventRecord *)arg1;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)init;

@end

